# Generated by Django 5.2.5 on 2026-07-13 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('citizen_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('street_address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('street', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('category', models.CharField(choices=[('Sanitation', 'Sanitation & Garbage'), ('Water', 'Water Supply & Sewage'), ('Streetlight', 'Streetlight Maintenance'), ('Roads', 'Roads & Potholes'), ('Encroachment', 'Encroachments & Building Control'), ('Others', 'Others')], max_length=50)),
                ('complaint_type', models.CharField(max_length=100)),
                ('social_media_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('video_upload', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_remarks', models.TextField(blank=True, null=True)),
                ('resolution_image', models.ImageField(blank=True, null=True, upload_to='resolutions/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.area')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='complaints.complaintstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaints/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='complaints.complaint')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.complaintstatus')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('Sanitation', 'Sanitation & Health'), ('WaterSupply', 'Water Supply'), ('StreetLights', 'Street Lights'), ('Roads', 'Roads & Works'), ('Revenue', 'Revenue & Tax'), ('General', 'General Administration')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.zone')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.officer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.ward'),
        ),
        migrations.AddField(
            model_name='area',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='complaints.ward'),
        ),
        migrations.AddField(
            model_name='ward',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='complaints.zone'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('zone', 'number')},
        ),
    ]
